### ISSUE TITLE
[Home] Añadir Campo Foto

### ISSUE THREAD

**Issue by pierregermain** [besutra/freeraum#3]
También me molaría que en la página de inicio cuando aparece una lista de propiedades, modificar los campos que aparecen, por ejemplo, incluir la foto.

**Comment by FerHervideas** [comment]
La cosa es meterse en:
Home > Administration > Structure > Content types > Property > Manage display 
Allí, pestaña "Teaser"

Buscar campo que se quiere incluir entre la lista de campos llamada "Disabled", y cambiar lo de "Hidden".

**Comment by pierregermain** [comment]
esto ya quedó. lo cierro.

recordar que esto es así porque se esta usando "Teaser" en la vista cómo display.
