### ISSUE TITLE
[Multilang] Es posible ?

### ISSUE THREAD

**Issue by pierregermain** [besutra/freeraum#9]
¿Si me pongo a traducir la web al español, sabes cómo podemos tener dos versiones, en inglés, la que está, y en español?

**Comment by pierregermain** [comment]
Pues se supone que en D8 (drupal 8) será posible usar multilang ... por ahora no te puedo contestar a esta pregunta.

Yo sinceramente prefiero hacerlo primero todo en un idioma y más adelante ver si se puede hacer multilang.

**Comment by FerHervideas** [comment]
Ok

**Comment by pierregermain** [comment]
hasta que no salga D8 dejamos este pendiente
